name: Convergence and accuracy tests

on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: "Install style numpy"
        run: pip install --user numpy
      - name: "Test nonlinear solvers"
        run: python -m unittest tests/test_nonlinear_solver.py
      - name: "Run convergence and accuracy tests"
        run: python -m unittest test_convergence_and_accuracy_simple_ode.py
      - name: "Run tests for van der Pol equation"
        run: python -m unittest tests/test_accuracy_van_der_pol_ode.py